import base64
import os
from tkinter import *
import screen_brightness_control as sbc

#ICON
icon = "AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABkPAAAZDwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABwAAAEoAAABaAAAAWQAAAFkAAABaAAAASgAAAAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABIAAADEAAAA9gAAAPkAAAD5AAAA9gAAAMQAAAASAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAKwAAAJQAAAD/AAAA/wAAAJQAAAArAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAoAAAAXAAAAGIAAABiAAAAYgAAAF0AAACoAAAA/wAAAP8AAACoAAAAXQAAAGIAAABiAAAAYgAAAFwAAAAoAAAA0wAAAPQAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAADrAAAA6wAAAOsAAAD0AAAA0wAAAP8AAACOAAAAKQAAAC0AAAAtAAAALQAAAC0AAAAtAAAALQAAAC0AAAAtAAAALQAAAC0AAAApAAAAjgAAAP8AAAD/AAAAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHYAAAD/AAAA/wAAAHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2AAAA/wAAAP8AAAB2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdgAAAP8AAAD/AAAAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHYAAAD/AAAA/wAAAHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB2AAAA/wAAAP8AAAB2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAdgAAAP8AAAD/AAAAdgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHYAAAD/AAAA/wAAAJcAAAA5AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADwAAAA8AAAAPAAAADkAAACXAAAA/wAAAMUAAADyAAAA7gAAAO4AAADuAAAA7gAAAO4AAADuAAAA7gAAAO4AAADuAAAA7gAAAO4AAADuAAAA8gAAAMUAAAAhAAAAUwAAAFoAAABZAAAAWQAAAFkAAABZAAAAWQAAAFkAAABZAAAAWQAAAFkAAABZAAAAWgAAAFMAAAAh8A8AAPAPAADwDwAAAAAAAAAAAAAAAAAAP/wAAD/8AAA//AAAP/wAAD/8AAA//AAAP/wAAAAAAAAAAAAAAAAAAA=="
icondata=base64.b64decode(icon)
tempFile = "icon.ico"
with open(tempFile, 'wb') as iconfile:
    iconfile.write(icondata)

def _set_value(val):
        sbc.set_brightness(int(val))
        pass

class GUI:
    def __init__(self):
        self.app = Tk()
        
        self.app.wm_iconbitmap(tempFile)
        os.remove(tempFile)
        self.app.title("Brightness Control")
        self._widgets()
        pass
    def _widgets(self):
        self.brightness = IntVar()
        self.slider = Scale(self.app, length=300,from_=0, to=100,orient=HORIZONTAL)
        self.slider.set(sbc.get_brightness())
        self.button = Button(self.app, text='Set', command=self._set_value)
        pass
    def _pack(self):
        self.slider.pack()
        self.button.pack()
        pass
    def _grid(self):
        self.slider.grid(row=0, column=0, rowspan=3)
        #self.button.grid(row=2, column=1, rowspan=1)
        pass
    def _set_value(self):
        sbc.set_brightness(self.slider.get())
    def _mainloop(self):
        self._pack()
        self.app.mainloop()
        pass
    def run(self):
        self._mainloop()
        pass

if __name__=="__main__":
    App = GUI()
    App.run()
    #os.remove(App.tempFile)